### ISSUE TITLE
Invalid Logo File

### ISSUE THREAD

**Issue by AchoArnold** [GDG-Bambili/devfest-mezam#4]
Our Logo file is invalid that is why we have this

<img width="1006" alt="screen shot 2015-09-28 at 19 28 34" src="https://cloud.githubusercontent.com/assets/4196457/10154286/50f7763c-665d-11e5-81d4-059751c97ac7.png">

This is our logo file https://github.com/GDG-Bambili/devfest-mezam/blob/master/app/images/logo.svg

We need to have something similar to the logo file for GDG Ukraine : https://github.com/gdg-x/hoverboard/blob/master/app/images/logo.svg

**Comment by Ch3ck** [comment]
Yeah, we will build all these designs once our budget is approved. We'll re work the image files for the DevFest. We are doing the best we can without the budget.
